language: python
python:
  - "3.4"
install:
  - sudo apt-get update
  - pip install python-coveralls
  - pip install -r requirements.txt
script:
  - "nosetests -v"
#- pep8 pgpbuddy
after_success:
  - coveralls 
