# Site settings
title: PGP Buddy
email: jen@redshiftzero.com
url: https://redshiftzero.github.io/pgpbuddy/
description: "Helping you set up and test your PGP configuration"
skills: "Test your PGP emailing setup and skills"
meta_author: Jennifer Helsby

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: redshiftzero and krasch 
  location: Issues
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/redshiftzero/pgpbuddy

# Postal address (add as many lines as necessary)
address:
  - line: 'Submit issues and suggestions <a href="https://github.com/redshiftzero/pgpbuddy">on Github</a>.'

# Credits content
credits: 'PGP Buddy is maintained by <a href="https://twitter.com/redshiftzero">redshiftzero</a> and <a href="https://twitter.com/krasch_io">krasch</a>. Comments and suggestions are welcome!'

# Build settings
markdown: kramdown
permalink: pretty
